### PR TITLE
filter() replacement, first ideas

### PR DESCRIPTION
**Pull request by swiftyy-mage**
Were you thinking something like this? If so, I would get rid of `_filter` and just filter in each method instead. `_filter` made sense when it would be fed a list with potentially more than one element, but I don't like calling it multiple times with a list of one element each time. Alternatively, I could just change it so it can only be fed a single function, not a list of them. Then I would call `_filter` in each method. Let me know what you think anyway. I can get this done quickly, it won't be hard.

### CODE REVIEW

**Comment by hbmartin** [comment]
@swiftyy-mage looks like a great start. I definitely don't think it's necessary to use `_filter`, especially if there's only one condition being applied. Easy to imagine it going away completely in the future.
One thing, not sure we need an `audio_only` function since we already have `get_audio_only` ?

**Comment by swiftyy-mage** [comment]
Yeah we should deffo keep it. `get_audio_only` returns the single audio only stream with the highest bitrate, `audio_only` returns the list of all audio only streams. Although I should probs change the names now you mention it, to avoid confusion.

**Comment by swiftyy-mage** [comment]
That's the actual functions done, I will do the tests next. I was thinking about OTF because it relies on `_filter` which I have deleted. Shouldn't we automatically filter out OTF streams, and then include a function that allows them to be seen? Given they can cause Errors, and that nobody seems to know what they are? Or are the errors not a problem anymore? I haven't really tested it in a while.

**Comment by swiftyy-mage** [comment]
Also, I deleted `is_dash`, because I think that DASH is just another word for adaptive right? Just to let you know, I am aware that many of the other methods do not work anymore, I will fix them too.

**Comment by swiftyy-mage** [comment]
Just added another commit straight after you made your comment, fixed the StreamQuery methods, added some docstrings which are probably wrong.
> hope I'm not too nitpicky

Nah my code is just messy as hell. Might just learn to code in 1's and 0's and hope nobody notices.

> Let's not delete `filter()` for now, it will break a lot of user code. Just annotate with `@deprecated`

Okay will correct this.

> Can things like abr and res take int arguments? They'll have to be string formatted in the filter for now, but will let us some day leave behind the horrible string sorting hacks.

Yeah was thinking about this too actually.

> Maybe _type can be renamed something like primary_type? Underscore prefix usually indicates a 'private' method, which I don't think is the intent here?

Fair enough.

> Aren't the bool args to `audio_only` and `video_only` implied by the function name? What's the user case for setting them to `False` ?

You might want to search only those streams which are not audio only or video only. Not sure why, but if anyone _did_ want to do this, I want it to be easy for them. Doesn't really hurt anyone leaving it in IMO.

> I don't think the Any import is necessary?

Derp

Will do this stuff and then get started on some unit tests. Seriously though I know my code is kinda a mess, It's something I am trying to fix but I've not had any formal training in this yet so thanks for being patient with me 😁

**Comment by swiftyy-mage** [comment]
Fixed some typing errors. Fixed the stuff you mentioned, but I gotta disagree with you on `audio_only` and `video_only` not needing args. You don't need to type `.audio_only(True)`, you would only need to type in `.audio_only(False)`, I just feel if we offer the user an option to do _**x**_, we should also offer them the option to not _**not x**_ where possible. But if you still want me to get rid of it I mean I'll do it no problem, I don't care that much because I admit it's an obscure feature. I'll get started on some tests, I need to read some of that stuff you linked me though first. Let me know what you think anyway. Not done any of the checks in Make Build yet because I think I should get the unit tests going first.

**Pull request closed without merging**
